DROP TABLE ARCHTYPES;
DROP TABLE CREATURE;
DROP TABLE SCENARIO;

CREATE TABLE SCENARIO(
SCENARIO_ID				VARCHAR(5)		PRIMARY KEY,
SCENARIO_NOTES			VARCHAR(100)			,
SCENARIO_CREATED		VARCHAR(100)	NOT NULL,
SCENARIO_CREATED_BY		VARCHAR(25)		NOT NULL,
GM_NOTES				VARCHAR(100)			,
IS_CUSTOM				VARCHAR(100)		
);

CREATE TABLE CREATURE(
CREATURE_ID			VARCHAR(5)		PRIMARY KEY,
SCENARIO_ID			VARCHAR(5)		NOT NULL,
CREATURE_NAME		VARCHAR(25) 	NOT NULL,
CREATURE_TYPE 		VARCHAR(25) 	NOT NULL,
FREQUENCY			VARCHAR(10)				,
RANDOM_MONSTER 		VARCHAR(3)				,
TERRAIN 			VARCHAR(25)				,
DESCRIPTION 		VARCHAR(100)			,
BACKGROUND 			VARCHAR(100)			,
ROLEPLAY 			VARCHAR(100)			,
SPECIAL_ATTACKS 	VARCHAR(100)			,
SPECIAL_DEFENSES 	VARCHAR(100)			,
FOREIGN KEY (SCENARIO_ID) REFERENCES SCENARIO(SCENARIO_ID)	
);

CREATE TABLE ARCHTYPES(
ARCHYTYPE_ID 		VARCHAR(5) 		PRIMARY KEY,
CREATURE_ID 		VARCHAR(5) 		NOT NULL,
ARCHYTYE_CLASS 		VARCHAR(25) 	NOT NULL,
HIT_POINTS 			VARCHAR(25) 	NOT NULL,
HT_P 				INTEGER 		DEFAULT 0,
A_LEVEL 			INTEGER 		DEFAULT 0 NOT NULL,
ARMOR_TYPE 			VARCHAR(25)				,
ARMOR_WORN 			VARCHAR(25)				,
WEAPON_TYPE 		VARCHAR(25)				,
DAMAGE 				VARCHAR(25)				,
DESCRIPTION			VARCHAR(100)			,
FOREIGN KEY (CREATURE_ID) REFERENCES CREATURE(CREATURE_ID)
);
